# Generated by Django 5.2.7 on 2025-11-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messaging',
            fields=[
                ('messageID', models.AutoField(primary_key=True, serialize=False)),
                ('senderID', models.CharField(max_length=255)),
                ('receiverID', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueueMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderID', models.CharField(max_length=255)),
                ('receiverID', models.CharField(max_length=255)),
                ('lastMessageID', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('senderID', 'receiverID'), name='uniqueName')],
            },
        ),
    ]
