# Generated by Django 5.2.7 on 2025-11-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messaging',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
