# Generated by Django 5.2.7 on 2025-11-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messaging_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messaging',
            name='is_read',
        ),
    ]
