# Generated by Django 5.2.7 on 2025-11-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('author_id', models.UUIDField()),
                ('title', models.TextField()),
                ('body', models.TextField()),
                ('rsvp_link', models.TextField(null=True)),
                ('event_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'announcements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRSVP',
            fields=[
                ('announcement_id', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'announcement_rsvps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('seller_id', models.UUIDField()),
                ('type', models.TextField()),
                ('category_id', models.IntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('price_cents', models.IntegerField()),
                ('condition_note', models.TextField(null=True)),
                ('status', models.TextField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('search_vector', models.TextField(null=True)),
            ],
            options={
                'db_table': 'listings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('listing_id', models.UUIDField()),
                ('url', models.TextField()),
                ('sort_order', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'listing_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListingTag',
            fields=[
                ('listing_id', models.UUIDField(primary_key=True, serialize=False)),
                ('tag_id', models.IntegerField()),
                ('created_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'listing_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MarketplaceUser',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('email_verified', models.BooleanField()),
                ('role', models.TextField()),
                ('password_hash', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.UUIDField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('bio', models.TextField(null=True)),
                ('avatar_url', models.TextField(null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
    ]
